-- Supabase Table Creation Script
-- Run this in the Supabase SQL Editor

CREATE TABLE public.soil_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT timezone('Asia/Jakarta'::text, now()) NOT NULL,
    "Hum" NUMERIC NOT NULL,
    "Temp" NUMERIC NOT NULL,
    "N" NUMERIC NOT NULL,
    "P" NUMERIC NOT NULL,
    "K" NUMERIC NOT NULL,
    "pH" NUMERIC NOT NULL,
    "EC" INTEGER NOT NULL,
    "OC_est" NUMERIC NOT NULL,
    ai_label TEXT,
    recommendation TEXT
);

-- Optional: Add an index on timestamp for faster queries
CREATE INDEX idx_soil_measurements_timestamp ON public.soil_measurements (timestamp);
